server:
  port: 8080
spring:
  application:
    name: multi-datasource-service
  datasource:
    dynamic:
      primary: order-ds
      datasource:
        order-ds:
          url: jdbc:mysql://127.0.0.1:3306/seata_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: root
        account-ds:
          url: jdbc:mysql://127.0.0.1:3306/seata_account?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: root
        storage-ds:
            url: jdbc:mysql://127.0.0.1:3306/seata_storage?useSSL=false&useUnicode=true&characterEncoding=UTF-8
            driver-class-name: com.mysql.jdbc.Driver
            username: root
            password: root
      #是否启动对 Seata 的集成
      seata: true

seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group #Seata事务组编号，用于 TC 集群名
  # 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      multi-datasource-service-group: default
    # 分组和 Seata 服务的映射
    grouplist:
      default: 127.0.0.1:8091
